# Spring Configuration
logging:
    level:
        ROOT: DEBUG
server:
    port: 8082
spring:
    application:
        name: jlearn
        base-url: http://127.0.0.1:8082
    config:
        import: credentials.yml
    # Datasource Configuration
    datasource:
        url: jdbc:mysql://localhost:3306/jlearn?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: Toan972002
        driver-class-name: com.mysql.cj.jdbc.Driver
    # Hibernate Configuration
    jpa:
        hibernate:
            ddl-auto: none
    # Liquibase Configuration
    liquibase:
        change-log: classpath:liquibase/master.xml
    # Mail Sender Configuration
    mail:
        host: smtp.gmail.com
        port: 587
